### ISSUE TITLE
Collections query at sprqlclient fails

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#241] opened 2024-01-11 13:11 UTC
https://meta.icos-cp.eu/sparqlclient/?q=Collections&type=CSV and choosing collection gives: 

assertion failed: Expected exactly one base64Binary value(s) of http://meta.icos-cp.eu/ontologies/cpmeta/hasSha256sum for https://meta.icos-cp.eu/collections/GiEh_gPaLM26VcmS8jlAFWS5, but got 0
org.eclipse.rdf4j.sail.SailException: assertion failed: Expected exactly one base64Binary value(s) of http://meta.icos-cp.eu/ontologies/cpmeta/hasSha256sum for https://meta.icos-cp.eu/collections/GiEh_gPaLM26VcmS8jlAFWS5, but got 0

**Comment by mirzov** [comment] 2024-01-11 13:54
There are three collections of collections present in our metadata, containing collection https://meta.icos-cp.eu/collections/GiEh_gPaLM26VcmS8jlAFWS5 as a member. However, the latter collection appears to have been purged (probably on explicit request from the creator), and therefore the composite collections got broken. Due to fragility of our metadata reading routines, the query breaks, as do the landing pages of the composite collections:
https://meta.icos-cp.eu/collections/AhL99iquKoAFzlUW8PwXaRvI
https://meta.icos-cp.eu/collections/PeSJi2wItqUkuH5GoDz-8sa8 
https://meta.icos-cp.eu/collections/DVZgivZnROyWcFpSyGDoMUAY

The fragility will be solved when PR #240 gets merged and deployed to production. Then it will be convenient to examine the broken collections and (likely) purge them, too.

Essentially this is not a software bug, just broken metadata and intentionally fragile reading routines.

**Comment by atverm** [comment] 2024-01-11 15:27
Maybe a similar problem here in the documents associated with this ecosystem NRT data object? : https://meta.icos-cp.eu/objects/TnjsrkID92Vdn1YSHBAVITlV, it links under Documentation to https://meta.icos-cp.eu/objects/_Vb_c34v0nfTA_fG0kiIAmXM and https://meta.icos-cp.eu/objects/tive6J2GP6n0kQcokzYXTr7W. Both urls give:

Data object not found
Expected exactly one values of property http://meta.icos-cp.eu/ontologies/cpmeta/hasObjectSpec for resource https://meta.icos-cp.eu/objects/_Vb_c34v0nfTA_fG0kiIAmXM, but got 0

**Comment by mirzov** [comment] 2024-01-12 09:34
> Maybe a similar problem here in the documents associated with this ecosystem NRT data object? : https://meta.icos-cp.eu/objects/TnjsrkID92Vdn1YSHBAVITlV, it links under Documentation to https://meta.icos-cp.eu/objects/_Vb_c34v0nfTA_fG0kiIAmXM and https://meta.icos-cp.eu/objects/tive6J2GP6n0kQcokzYXTr7W.

That was an unrelated regression, that was speedily fixed. The document landing pages work now.

Also, now that the PR #240 is merged and deployed, we can conveniently examine the broken collections and see which ones should be purged.

**Comment by mirzov** [comment] 2024-01-15 14:46
The broken collections have been purged, and the original issue has been fixed in PR #240 .

**Closed by mirzov** 2024-01-15 14:46 UTC
Labels: bug
